"use client"

import { useState } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { GitPullRequest, Loader2, CheckCircle2, AlertCircle } from "lucide-react"
import { useGitHub } from "@/hooks/use-github"

interface CreatePRButtonProps {
  repoId: string
  githubRepoFullName: string
  installationId: number
  onPRCreated?: (prUrl: string) => void
  disabled?: boolean
}

export function CreatePRButton({
  repoId,
  githubRepoFullName,
  installationId,
  onPRCreated,
  disabled = false,
}: CreatePRButtonProps) {
  const [open, setOpen] = useState(false)
  const [commitMessage, setCommitMessage] = useState(
    "docs: Add generated docstrings via CodeIQ"
  )
  const [prTitle, setPrTitle] = useState("docs: Add comprehensive docstrings")
  const [prBody, setPrBody] = useState(
    "This PR adds comprehensive docstrings generated by CodeIQ\n\n" +
      "## Changes\n" +
      "- Added comprehensive docstrings to all functions and classes\n" +
      "- Documented parameters, return types, and exceptions\n" +
      "- Generated using the CodeIQ documentation pipeline\n\n" +
      "## Review Notes\n" +
      "Please review the generated documentation and make any necessary adjustments."
  )

  const { createPR, loading, error } = useGitHub()
  const [prResult, setPrResult] = useState<any>(null)
  const [prError, setPrError] = useState<string | null>(null)

  const handleCreatePR = async () => {
    setPrError(null)
    const result = await createPR(
      repoId,
      githubRepoFullName,
      installationId,
      commitMessage,
      prTitle,
      prBody
    )

    if (result?.pr_url) {
      setPrResult(result)
      onPRCreated?.(result.pr_url)

      // Auto-open the PR in a new tab
      setTimeout(() => {
        window.open(result.pr_url, "_blank")
      }, 500)
    } else if (error) {
      setPrError(error)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button
          className="gap-2"
          disabled={disabled || !installationId}
          title={
            !installationId
              ? "CodeIQ GitHub App must be installed"
              : undefined
          }
        >
          <GitPullRequest className="w-4 h-4" />
          Create Pull Request
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitPullRequest className="w-5 h-5" />
            Create Pull Request
          </DialogTitle>
          <DialogDescription>
            Create a PR to merge the generated docstrings into{" "}
            <Badge variant="outline">{githubRepoFullName}</Badge>
          </DialogDescription>
        </DialogHeader>

        {prResult ? (
          <div className="space-y-4">
            <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-4 flex gap-3">
              <CheckCircle2 className="w-5 h-5 text-emerald-600 flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <h4 className="font-semibold text-emerald-900">
                  Pull Request Created!
                </h4>
                <p className="text-sm text-emerald-700 mt-1">
                  PR #{prResult.pr_number}: {prResult.pr_title}
                </p>
                <a
                  href={prResult.pr_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-sm text-emerald-600 hover:text-emerald-700 underline mt-2 inline-block"
                >
                  View on GitHub →
                </a>
              </div>
            </div>

            <div className="flex gap-2 justify-end">
              <Button
                variant="outline"
                onClick={() => {
                  setOpen(false)
                  setPrResult(null)
                }}
              >
                Close
              </Button>
              <Button
                onClick={() =>
                  window.open(prResult.pr_url, "_blank")
                }
              >
                Open PR
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {prError && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex gap-3">
                <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm text-red-700">{prError}</p>
                </div>
              </div>
            )}

            <div className="space-y-2">
              <label className="text-sm font-medium">Commit Message</label>
              <Input
                value={commitMessage}
                onChange={(e) => setCommitMessage(e.target.value)}
                placeholder="Enter commit message"
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">PR Title</label>
              <Input
                value={prTitle}
                onChange={(e) => setPrTitle(e.target.value)}
                placeholder="Enter PR title"
              />
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">PR Description</label>
              <Textarea
                value={prBody}
                onChange={(e) => setPrBody(e.target.value)}
                placeholder="Enter PR description"
                rows={8}
              />
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 flex gap-2">
              <AlertCircle className="w-4 h-4 text-blue-600 flex-shrink-0 mt-0.5" />
              <p className="text-xs text-blue-700">
                This will create a new branch, commit your generated
                documentation, and open a PR for review.
              </p>
            </div>

            <div className="flex gap-2 justify-end">
              <Button
                variant="outline"
                onClick={() => setOpen(false)}
                disabled={loading}
              >
                Cancel
              </Button>
              <Button
                onClick={handleCreatePR}
                disabled={loading || !commitMessage.trim() || !prTitle.trim()}
                className="gap-2"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Creating...
                  </>
                ) : (
                  <>
                    <GitPullRequest className="w-4 h-4" />
                    Create PR
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}
