"""
Models for GitHub integration.

Tracks GitHub OAuth tokens, App installations, and related metadata.
"""

from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class GitHubUser(BaseModel):
    """GitHub user information from OAuth"""
    github_id: int                      # GitHub user ID
    github_login: str                   # GitHub username
    github_avatar_url: Optional[str] = None
    access_token: str                   # OAuth access token for user repos
    expires_at: Optional[datetime] = None
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class GitHubAppInstallation(BaseModel):
    """CodeIQ GitHub App installation for a repository"""
    installation_id: int                # GitHub App installation ID
    repository_id: int                  # GitHub repository ID
    repository_name: str                # Repository name (owner/repo)
    owner_login: str                    # Repository owner login
    is_installed: bool = True
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class GitHubRepository(BaseModel):
    """GitHub repository information"""
    github_repo_id: int
    owner: str
    name: str
    full_name: str
    description: Optional[str] = None
    url: str
    clone_url: str
    private: bool = False
    language: Optional[str] = None
    stars: int = 0
    installation_id: Optional[int] = None  # If CodeIQ GitHub App is installed
    app_installed: bool = False


class GitHubDocstringPR(BaseModel):
    """Tracks PR creation for docstring generation"""
    repo_id: str                        # CodeIQ repo ID
    github_repo_full_name: str          # owner/repo
    installation_id: int                # GitHub App installation ID
    pr_number: Optional[int] = None
    pr_url: Optional[str] = None
    branch_name: str = "codeiq-docs-update"
    status: str = "pending"             # pending | created | merged | failed
    error_message: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


# ── Request/Response Models ──

class GitHubUserProfileResponse(BaseModel):
    """Response with GitHub user profile info"""
    github_id: int
    github_login: str
    github_avatar_url: Optional[str] = None
    repositories: list = Field(default_factory=list)


class AuthorizeGitHubRequest(BaseModel):
    """Request to authorize GitHub OAuth"""
    code: str
    state: Optional[str] = None


class CreatePRRequest(BaseModel):
    """Request to create a PR with generated docstrings"""
    repo_id: str                        # CodeIQ repo ID
    github_repo_full_name: str
    installation_id: int
    commit_message: str = "docs: Add generated docstrings via CodeIQ"
    pr_title: str = "docs: Add comprehensive docstrings"
    pr_body: str = "This PR adds comprehensive docstrings generated by CodeIQ"


class InstallationWebhookPayload(BaseModel):
    """GitHub App installation webhook payload"""
    action: str                         # installed | uninstalled | created | deleted
    installation: Dict[str, Any]
    repositories: Optional[list] = None
    sender: Dict[str, Any]